// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	Action       string
	ResourceType pgtype.Text
	ResourceID   pgtype.UUID
	IpAddress    *netip.Addr
	UserAgent    pgtype.Text
	Metadata     []byte
	CreatedAt    pgtype.Timestamp
}

type RecoveryCode struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	CodeHash  string
	UsedAt    pgtype.Timestamp
	CreatedAt pgtype.Timestamp
}

type Session struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	TokenHash  string
	DeviceName pgtype.Text
	IpAddress  *netip.Addr
	UserAgent  pgtype.Text
	CreatedAt  pgtype.Timestamp
	ExpiresAt  pgtype.Timestamp
	RevokedAt  pgtype.Timestamp
}

type SharedVaultItem struct {
	ID               pgtype.UUID
	VaultItemID      pgtype.UUID
	OwnerID          pgtype.UUID
	SharedWithUserID pgtype.UUID
	EncryptedItemKey []byte
	Permission       string
	CreatedAt        pgtype.Timestamp
}

type User struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
	LastLoginAt  pgtype.Timestamp
	IsActive     pgtype.Bool
	MfaEnabled   pgtype.Bool
	MfaSecret    pgtype.Text
}

type VaultItem struct {
	ID            pgtype.UUID
	UserID        pgtype.UUID
	EncryptedData []byte
	ItemType      string
	Title         pgtype.Text
	Folder        pgtype.Text
	Tags          []string
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
	DeletedAt     pgtype.Timestamp
	Version       pgtype.Int4
}
