// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recovery_codes.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRecoveryCode = `-- name: CreateRecoveryCode :one
INSERT INTO recovery_codes (user_id, code_hash, created_at)
VALUES ($1, $2, NOW())
RETURNING id, user_id, code_hash, used_at, created_at
`

type CreateRecoveryCodeParams struct {
	UserID   pgtype.UUID
	CodeHash string
}

func (q *Queries) CreateRecoveryCode(ctx context.Context, arg CreateRecoveryCodeParams) (RecoveryCode, error) {
	row := q.db.QueryRow(ctx, createRecoveryCode, arg.UserID, arg.CodeHash)
	var i RecoveryCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CodeHash,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRecoveryCodesByUserID = `-- name: DeleteRecoveryCodesByUserID :exec
DELETE FROM recovery_codes WHERE user_id = $1
`

func (q *Queries) DeleteRecoveryCodesByUserID(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRecoveryCodesByUserID, userID)
	return err
}

const listUnusedRecoveryCodesByUserID = `-- name: ListUnusedRecoveryCodesByUserID :many
SELECT id, user_id, code_hash, used_at, created_at
FROM recovery_codes
WHERE user_id = $1
  AND used_at IS NULL
`

func (q *Queries) ListUnusedRecoveryCodesByUserID(ctx context.Context, userID pgtype.UUID) ([]RecoveryCode, error) {
	rows, err := q.db.Query(ctx, listUnusedRecoveryCodesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecoveryCode
	for rows.Next() {
		var i RecoveryCode
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CodeHash,
			&i.UsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRecoveryCodeUsed = `-- name: MarkRecoveryCodeUsed :execrows
UPDATE recovery_codes
SET used_at = NOW()
WHERE id = $1
  AND used_at IS NULL
`

func (q *Queries) MarkRecoveryCodeUsed(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markRecoveryCodeUsed, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
