// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlc

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, token_hash, device_name, ip_address, user_agent, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, token_hash, device_name, ip_address, user_agent, created_at, expires_at, revoked_at
`

type CreateSessionParams struct {
	UserID     pgtype.UUID
	TokenHash  string
	DeviceName pgtype.Text
	IpAddress  *netip.Addr
	UserAgent  pgtype.Text
	CreatedAt  pgtype.Timestamp
	ExpiresAt  pgtype.Timestamp
}

type CreateSessionRow struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	TokenHash  string
	DeviceName pgtype.Text
	IpAddress  *netip.Addr
	UserAgent  pgtype.Text
	CreatedAt  pgtype.Timestamp
	ExpiresAt  pgtype.Timestamp
	RevokedAt  pgtype.Timestamp
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (CreateSessionRow, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.TokenHash,
		arg.DeviceName,
		arg.IpAddress,
		arg.UserAgent,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i CreateSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.DeviceName,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, user_id, token_hash, device_name, ip_address, user_agent,
       created_at, expires_at, revoked_at
FROM sessions
WHERE id = $1
  AND revoked_at IS NULL
  AND expires_at > NOW()
`

type GetSessionByIDRow struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	TokenHash  string
	DeviceName pgtype.Text
	IpAddress  *netip.Addr
	UserAgent  pgtype.Text
	CreatedAt  pgtype.Timestamp
	ExpiresAt  pgtype.Timestamp
	RevokedAt  pgtype.Timestamp
}

func (q *Queries) GetSessionByID(ctx context.Context, id pgtype.UUID) (GetSessionByIDRow, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i GetSessionByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.DeviceName,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getSessionByPreviousTokenHash = `-- name: GetSessionByPreviousTokenHash :one
SELECT id, user_id, token_hash, device_name, ip_address, user_agent, created_at, expires_at, revoked_at, previous_token_hash, token_rotated_at
FROM sessions
WHERE previous_token_hash = $1
  AND revoked_at IS NULL
  AND expires_at > NOW()
`

func (q *Queries) GetSessionByPreviousTokenHash(ctx context.Context, previousTokenHash pgtype.Text) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByPreviousTokenHash, previousTokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.DeviceName,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.PreviousTokenHash,
		&i.TokenRotatedAt,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, user_id, token_hash, device_name, ip_address, user_agent, created_at, expires_at, revoked_at
FROM sessions
WHERE token_hash = $1
  AND revoked_at IS NULL
  AND expires_at > NOW()
`

type GetSessionByTokenHashRow struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	TokenHash  string
	DeviceName pgtype.Text
	IpAddress  *netip.Addr
	UserAgent  pgtype.Text
	CreatedAt  pgtype.Timestamp
	ExpiresAt  pgtype.Timestamp
	RevokedAt  pgtype.Timestamp
}

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.DeviceName,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const listSessionsByUserID = `-- name: ListSessionsByUserID :many
SELECT id, user_id, device_name, ip_address, user_agent, created_at, expires_at, revoked_at
FROM sessions
WHERE user_id = $1
  AND revoked_at IS NULL
  AND expires_at > NOW()
ORDER BY created_at DESC
`

type ListSessionsByUserIDRow struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	DeviceName pgtype.Text
	IpAddress  *netip.Addr
	UserAgent  pgtype.Text
	CreatedAt  pgtype.Timestamp
	ExpiresAt  pgtype.Timestamp
	RevokedAt  pgtype.Timestamp
}

func (q *Queries) ListSessionsByUserID(ctx context.Context, userID pgtype.UUID) ([]ListSessionsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listSessionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionsByUserIDRow
	for rows.Next() {
		var i ListSessionsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeviceName,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSession = `-- name: RevokeSession :execrows
UPDATE sessions
SET revoked_at = NOW()
WHERE id = $1
  AND revoked_at IS NULL
  AND user_id = $2
`

type RevokeSessionParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSession, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeSessionsExcept = `-- name: RevokeSessionsExcept :exec
UPDATE sessions
SET revoked_at = NOW()
WHERE user_id = $1
  AND id <> $2
  AND revoked_at IS NULL
`

type RevokeSessionsExceptParams struct {
	UserID pgtype.UUID
	ID     pgtype.UUID
}

func (q *Queries) RevokeSessionsExcept(ctx context.Context, arg RevokeSessionsExceptParams) error {
	_, err := q.db.Exec(ctx, revokeSessionsExcept, arg.UserID, arg.ID)
	return err
}

const rotateSessionToken = `-- name: RotateSessionToken :execrows
UPDATE sessions
SET previous_token_hash = token_hash,
    token_hash = $2,
    token_rotated_at = NOW()
WHERE id = $1
  AND token_hash = $3
  AND revoked_at IS NULL
  AND expires_at > NOW()
`

type RotateSessionTokenParams struct {
	ID          pgtype.UUID
	TokenHash   string
	TokenHash_2 string
}

func (q *Queries) RotateSessionToken(ctx context.Context, arg RotateSessionTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, rotateSessionToken, arg.ID, arg.TokenHash, arg.TokenHash_2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rotateSessionTokenFromPrevious = `-- name: RotateSessionTokenFromPrevious :execrows
UPDATE sessions
SET previous_token_hash = token_hash,
    token_hash = $2,
    token_rotated_at = NOW()
WHERE id = $1
  AND previous_token_hash = $3
  AND token_rotated_at > $4
  AND revoked_at IS NULL
  AND expires_at > NOW()
`

type RotateSessionTokenFromPreviousParams struct {
	ID                pgtype.UUID
	TokenHash         string
	PreviousTokenHash pgtype.Text
	TokenRotatedAt    pgtype.Timestamp
}

func (q *Queries) RotateSessionTokenFromPrevious(ctx context.Context, arg RotateSessionTokenFromPreviousParams) (int64, error) {
	result, err := q.db.Exec(ctx, rotateSessionTokenFromPrevious,
		arg.ID,
		arg.TokenHash,
		arg.PreviousTokenHash,
		arg.TokenRotatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
