// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shared_vault_items.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSharedVaultItemsForUser = `-- name: CountSharedVaultItemsForUser :one
SELECT COUNT(*)
FROM shared_vault_items s
INNER JOIN vault_items v ON v.id = s.vault_item_id
WHERE s.shared_with_user_id = $1
  AND v.deleted_at IS NULL
`

func (q *Queries) CountSharedVaultItemsForUser(ctx context.Context, sharedWithUserID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSharedVaultItemsForUser, sharedWithUserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSharedVaultItem = `-- name: CreateSharedVaultItem :one
INSERT INTO shared_vault_items (vault_item_id, owner_id, shared_with_user_id, encrypted_item_key, permission, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, vault_item_id, owner_id, shared_with_user_id, encrypted_item_key, permission, created_at
`

type CreateSharedVaultItemParams struct {
	VaultItemID      pgtype.UUID
	OwnerID          pgtype.UUID
	SharedWithUserID pgtype.UUID
	EncryptedItemKey []byte
	Permission       string
	CreatedAt        pgtype.Timestamp
}

func (q *Queries) CreateSharedVaultItem(ctx context.Context, arg CreateSharedVaultItemParams) (SharedVaultItem, error) {
	row := q.db.QueryRow(ctx, createSharedVaultItem,
		arg.VaultItemID,
		arg.OwnerID,
		arg.SharedWithUserID,
		arg.EncryptedItemKey,
		arg.Permission,
		arg.CreatedAt,
	)
	var i SharedVaultItem
	err := row.Scan(
		&i.ID,
		&i.VaultItemID,
		&i.OwnerID,
		&i.SharedWithUserID,
		&i.EncryptedItemKey,
		&i.Permission,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSharedVaultItem = `-- name: DeleteSharedVaultItem :execrows
DELETE FROM shared_vault_items
WHERE vault_item_id = $1
  AND owner_id = $2
  AND shared_with_user_id = $3
`

type DeleteSharedVaultItemParams struct {
	VaultItemID      pgtype.UUID
	OwnerID          pgtype.UUID
	SharedWithUserID pgtype.UUID
}

func (q *Queries) DeleteSharedVaultItem(ctx context.Context, arg DeleteSharedVaultItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSharedVaultItem, arg.VaultItemID, arg.OwnerID, arg.SharedWithUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getShareByVaultAndRecipient = `-- name: GetShareByVaultAndRecipient :one
SELECT id, vault_item_id, owner_id, shared_with_user_id, encrypted_item_key, permission, created_at
FROM shared_vault_items
WHERE vault_item_id = $1
  AND shared_with_user_id = $2
`

type GetShareByVaultAndRecipientParams struct {
	VaultItemID      pgtype.UUID
	SharedWithUserID pgtype.UUID
}

func (q *Queries) GetShareByVaultAndRecipient(ctx context.Context, arg GetShareByVaultAndRecipientParams) (SharedVaultItem, error) {
	row := q.db.QueryRow(ctx, getShareByVaultAndRecipient, arg.VaultItemID, arg.SharedWithUserID)
	var i SharedVaultItem
	err := row.Scan(
		&i.ID,
		&i.VaultItemID,
		&i.OwnerID,
		&i.SharedWithUserID,
		&i.EncryptedItemKey,
		&i.Permission,
		&i.CreatedAt,
	)
	return i, err
}

const listSharedVaultItemsForUser = `-- name: ListSharedVaultItemsForUser :many
SELECT
  s.id,
  s.vault_item_id,
  s.owner_id,
  s.shared_with_user_id,
  s.encrypted_item_key,
  s.permission,
  s.created_at,
  v.id AS item_id,
  v.user_id AS item_user_id,
  v.encrypted_data AS item_encrypted_data,
  v.item_type AS item_item_type,
  v.title AS item_title,
  v.folder AS item_folder,
  v.tags AS item_tags,
  v.created_at AS item_created_at,
  v.updated_at AS item_updated_at,
  v.deleted_at AS item_deleted_at,
  v.version AS item_version
FROM shared_vault_items s
INNER JOIN vault_items v ON v.id = s.vault_item_id
WHERE s.shared_with_user_id = $1
  AND v.deleted_at IS NULL
ORDER BY s.created_at DESC
LIMIT $2 OFFSET $3
`

type ListSharedVaultItemsForUserParams struct {
	SharedWithUserID pgtype.UUID
	Limit            int32
	Offset           int32
}

type ListSharedVaultItemsForUserRow struct {
	ID                pgtype.UUID
	VaultItemID       pgtype.UUID
	OwnerID           pgtype.UUID
	SharedWithUserID  pgtype.UUID
	EncryptedItemKey  []byte
	Permission        string
	CreatedAt         pgtype.Timestamp
	ItemID            pgtype.UUID
	ItemUserID        pgtype.UUID
	ItemEncryptedData []byte
	ItemItemType      string
	ItemTitle         pgtype.Text
	ItemFolder        pgtype.Text
	ItemTags          []string
	ItemCreatedAt     pgtype.Timestamp
	ItemUpdatedAt     pgtype.Timestamp
	ItemDeletedAt     pgtype.Timestamp
	ItemVersion       pgtype.Int4
}

func (q *Queries) ListSharedVaultItemsForUser(ctx context.Context, arg ListSharedVaultItemsForUserParams) ([]ListSharedVaultItemsForUserRow, error) {
	rows, err := q.db.Query(ctx, listSharedVaultItemsForUser, arg.SharedWithUserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSharedVaultItemsForUserRow
	for rows.Next() {
		var i ListSharedVaultItemsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.VaultItemID,
			&i.OwnerID,
			&i.SharedWithUserID,
			&i.EncryptedItemKey,
			&i.Permission,
			&i.CreatedAt,
			&i.ItemID,
			&i.ItemUserID,
			&i.ItemEncryptedData,
			&i.ItemItemType,
			&i.ItemTitle,
			&i.ItemFolder,
			&i.ItemTags,
			&i.ItemCreatedAt,
			&i.ItemUpdatedAt,
			&i.ItemDeletedAt,
			&i.ItemVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
