// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, created_at, updated_at, is_active, mfa_enabled, mfa_secret)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, email, password_hash, created_at, updated_at, is_active, mfa_enabled, mfa_secret
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
	IsActive     pgtype.Bool
	MfaEnabled   pgtype.Bool
	MfaSecret    pgtype.Text
}

type CreateUserRow struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
	IsActive     pgtype.Bool
	MfaEnabled   pgtype.Bool
	MfaSecret    pgtype.Text
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.IsActive,
		arg.MfaEnabled,
		arg.MfaSecret,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
		&i.MfaEnabled,
		&i.MfaSecret,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, created_at, updated_at, is_active, mfa_enabled, mfa_secret
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
	IsActive     pgtype.Bool
	MfaEnabled   pgtype.Bool
	MfaSecret    pgtype.Text
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
		&i.MfaEnabled,
		&i.MfaSecret,
	)
	return i, err
}
