// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const confirmMFA = `-- name: ConfirmMFA :exec
UPDATE users SET mfa_enabled = TRUE, updated_at = NOW() WHERE id = $1
`

func (q *Queries) ConfirmMFA(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, confirmMFA, id)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, created_at, updated_at, is_active, mfa_enabled, mfa_secret)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, email, password_hash, created_at, updated_at, is_active, mfa_enabled, mfa_secret
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
	IsActive     pgtype.Bool
	MfaEnabled   pgtype.Bool
	MfaSecret    pgtype.Text
}

type CreateUserRow struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
	IsActive     pgtype.Bool
	MfaEnabled   pgtype.Bool
	MfaSecret    pgtype.Text
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.IsActive,
		arg.MfaEnabled,
		arg.MfaSecret,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
		&i.MfaEnabled,
		&i.MfaSecret,
	)
	return i, err
}

const disableMFA = `-- name: DisableMFA :exec
UPDATE users SET mfa_enabled = FALSE, mfa_secret = NULL, updated_at = NOW() WHERE id = $1
`

func (q *Queries) DisableMFA(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, disableMFA, id)
	return err
}

const enableMFASecret = `-- name: EnableMFASecret :exec
UPDATE users SET mfa_secret = $2, updated_at = NOW() WHERE id = $1
`

type EnableMFASecretParams struct {
	ID        pgtype.UUID
	MfaSecret pgtype.Text
}

func (q *Queries) EnableMFASecret(ctx context.Context, arg EnableMFASecretParams) error {
	_, err := q.db.Exec(ctx, enableMFASecret, arg.ID, arg.MfaSecret)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, created_at, updated_at, is_active, mfa_enabled, mfa_secret
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
	IsActive     pgtype.Bool
	MfaEnabled   pgtype.Bool
	MfaSecret    pgtype.Text
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
		&i.MfaEnabled,
		&i.MfaSecret,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, created_at, updated_at, is_active, mfa_enabled, mfa_secret
FROM users 
WHERE id = $1
`

type GetUserByIDRow struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
	IsActive     pgtype.Bool
	MfaEnabled   pgtype.Bool
	MfaSecret    pgtype.Text
}

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
		&i.MfaEnabled,
		&i.MfaSecret,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :execrows
UPDATE users
SET password_hash = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           pgtype.UUID
	PasswordHash string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
