// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vault_items.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVaultItem = `-- name: CreateVaultItem :one
INSERT INTO vault_items (user_id, encrypted_data, item_type, title, folder, tags, created_at, updated_at, version)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, encrypted_data, item_type, title, folder, tags, created_at, updated_at, deleted_at, version
`

type CreateVaultItemParams struct {
	UserID        pgtype.UUID
	EncryptedData []byte
	ItemType      string
	Title         pgtype.Text
	Folder        pgtype.Text
	Tags          []string
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
	Version       pgtype.Int4
}

func (q *Queries) CreateVaultItem(ctx context.Context, arg CreateVaultItemParams) (VaultItem, error) {
	row := q.db.QueryRow(ctx, createVaultItem,
		arg.UserID,
		arg.EncryptedData,
		arg.ItemType,
		arg.Title,
		arg.Folder,
		arg.Tags,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Version,
	)
	var i VaultItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EncryptedData,
		&i.ItemType,
		&i.Title,
		&i.Folder,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
	)
	return i, err
}

const getVaultItemByID = `-- name: GetVaultItemByID :one
SELECT id, user_id, encrypted_data, item_type, title, folder, tags, created_at, updated_at, deleted_at, version
FROM vault_items
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetVaultItemByID(ctx context.Context, id pgtype.UUID) (VaultItem, error) {
	row := q.db.QueryRow(ctx, getVaultItemByID, id)
	var i VaultItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EncryptedData,
		&i.ItemType,
		&i.Title,
		&i.Folder,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
	)
	return i, err
}

const listVaultItemsByUserID = `-- name: ListVaultItemsByUserID :many
SELECT id, user_id, encrypted_data, item_type, title, folder, tags, created_at, updated_at, deleted_at, version
FROM vault_items
WHERE user_id = $1
  AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListVaultItemsByUserID(ctx context.Context, userID pgtype.UUID) ([]VaultItem, error) {
	rows, err := q.db.Query(ctx, listVaultItemsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VaultItem
	for rows.Next() {
		var i VaultItem
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EncryptedData,
			&i.ItemType,
			&i.Title,
			&i.Folder,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
