// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vault_items.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countVaultItemsFiltered = `-- name: CountVaultItemsFiltered :one
SELECT COUNT(*)
FROM vault_items
WHERE user_id = $1
  AND deleted_at IS NULL
  AND (NULLIF($2, '') IS NULL OR folder = $2)
  AND (NULLIF($3, '') IS NULL OR item_type = $3)
  AND (NULLIF($4, '') IS NULL OR $4 = ANY(tags))
  AND (NULLIF($5, '') IS NULL OR title ILIKE '%' || $5 || '%')
`

type CountVaultItemsFilteredParams struct {
	UserID  pgtype.UUID
	Column2 interface{}
	Column3 interface{}
	Column4 interface{}
	Column5 interface{}
}

func (q *Queries) CountVaultItemsFiltered(ctx context.Context, arg CountVaultItemsFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countVaultItemsFiltered,
		arg.UserID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVaultItem = `-- name: CreateVaultItem :one
INSERT INTO vault_items (user_id, encrypted_data, item_type, title, folder, tags, created_at, updated_at, version)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, encrypted_data, item_type, title, folder, tags, created_at, updated_at, deleted_at, version
`

type CreateVaultItemParams struct {
	UserID        pgtype.UUID
	EncryptedData []byte
	ItemType      string
	Title         pgtype.Text
	Folder        pgtype.Text
	Tags          []string
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
	Version       pgtype.Int4
}

func (q *Queries) CreateVaultItem(ctx context.Context, arg CreateVaultItemParams) (VaultItem, error) {
	row := q.db.QueryRow(ctx, createVaultItem,
		arg.UserID,
		arg.EncryptedData,
		arg.ItemType,
		arg.Title,
		arg.Folder,
		arg.Tags,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Version,
	)
	var i VaultItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EncryptedData,
		&i.ItemType,
		&i.Title,
		&i.Folder,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
	)
	return i, err
}

const deleteVaultItem = `-- name: DeleteVaultItem :one
UPDATE vault_items  
SET deleted_at = NOW(), version = version + 1
WHERE id = $1
  AND deleted_at IS NULL
  AND version = $2
RETURNING id, user_id, encrypted_data, item_type, title, folder, tags, created_at, updated_at, deleted_at, version
`

type DeleteVaultItemParams struct {
	ID      pgtype.UUID
	Version pgtype.Int4
}

func (q *Queries) DeleteVaultItem(ctx context.Context, arg DeleteVaultItemParams) (VaultItem, error) {
	row := q.db.QueryRow(ctx, deleteVaultItem, arg.ID, arg.Version)
	var i VaultItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EncryptedData,
		&i.ItemType,
		&i.Title,
		&i.Folder,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
	)
	return i, err
}

const getVaultItemByID = `-- name: GetVaultItemByID :one
SELECT id, user_id, encrypted_data, item_type, title, folder, tags, created_at, updated_at, deleted_at, version
FROM vault_items
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetVaultItemByID(ctx context.Context, id pgtype.UUID) (VaultItem, error) {
	row := q.db.QueryRow(ctx, getVaultItemByID, id)
	var i VaultItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EncryptedData,
		&i.ItemType,
		&i.Title,
		&i.Folder,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
	)
	return i, err
}

const listVaultItemsByUserID = `-- name: ListVaultItemsByUserID :many
SELECT id, user_id, encrypted_data, item_type, title, folder, tags, created_at, updated_at, deleted_at, version
FROM vault_items
WHERE user_id = $1
  AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListVaultItemsByUserID(ctx context.Context, userID pgtype.UUID) ([]VaultItem, error) {
	rows, err := q.db.Query(ctx, listVaultItemsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VaultItem
	for rows.Next() {
		var i VaultItem
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EncryptedData,
			&i.ItemType,
			&i.Title,
			&i.Folder,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVaultItemsFiltered = `-- name: ListVaultItemsFiltered :many
SELECT id, user_id, encrypted_data, item_type, title, folder, tags, created_at, updated_at, deleted_at, version
FROM vault_items
WHERE user_id = $1
  AND deleted_at IS NULL
  AND (NULLIF($2, '') IS NULL OR folder = $2)
  AND (NULLIF($3, '') IS NULL OR item_type = $3)
  AND (NULLIF($4, '') IS NULL OR $4 = ANY(tags))
  AND (NULLIF($5, '') IS NULL OR title ILIKE '%' || $5 || '%')
ORDER BY created_at DESC
LIMIT $6 OFFSET $7
`

type ListVaultItemsFilteredParams struct {
	UserID  pgtype.UUID
	Column2 interface{}
	Column3 interface{}
	Column4 interface{}
	Column5 interface{}
	Limit   int32
	Offset  int32
}

func (q *Queries) ListVaultItemsFiltered(ctx context.Context, arg ListVaultItemsFilteredParams) ([]VaultItem, error) {
	rows, err := q.db.Query(ctx, listVaultItemsFiltered,
		arg.UserID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VaultItem
	for rows.Next() {
		var i VaultItem
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EncryptedData,
			&i.ItemType,
			&i.Title,
			&i.Folder,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreVaultItem = `-- name: RestoreVaultItem :one
UPDATE vault_items
SET deleted_at = NULL, version = version + 1
WHERE id = $1
  AND deleted_at IS NOT NULL
  AND version = $2
  AND user_id = $3
RETURNING id, user_id, encrypted_data, item_type, title, folder, tags, created_at, updated_at, deleted_at, version
`

type RestoreVaultItemParams struct {
	ID      pgtype.UUID
	Version pgtype.Int4
	UserID  pgtype.UUID
}

func (q *Queries) RestoreVaultItem(ctx context.Context, arg RestoreVaultItemParams) (VaultItem, error) {
	row := q.db.QueryRow(ctx, restoreVaultItem, arg.ID, arg.Version, arg.UserID)
	var i VaultItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EncryptedData,
		&i.ItemType,
		&i.Title,
		&i.Folder,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
	)
	return i, err
}

const updateVaultItem = `-- name: UpdateVaultItem :one
UPDATE vault_items
SET encrypted_data = $2, item_type = $3, title = $4, folder = $5, tags = $6, updated_at = $7, version = version + 1
WHERE id = $1
  AND deleted_at IS NULL
  AND version = $8
RETURNING id, user_id, encrypted_data, item_type, title, folder, tags, created_at, updated_at, deleted_at, version
`

type UpdateVaultItemParams struct {
	ID            pgtype.UUID
	EncryptedData []byte
	ItemType      string
	Title         pgtype.Text
	Folder        pgtype.Text
	Tags          []string
	UpdatedAt     pgtype.Timestamp
	Version       pgtype.Int4
}

func (q *Queries) UpdateVaultItem(ctx context.Context, arg UpdateVaultItemParams) (VaultItem, error) {
	row := q.db.QueryRow(ctx, updateVaultItem,
		arg.ID,
		arg.EncryptedData,
		arg.ItemType,
		arg.Title,
		arg.Folder,
		arg.Tags,
		arg.UpdatedAt,
		arg.Version,
	)
	var i VaultItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EncryptedData,
		&i.ItemType,
		&i.Title,
		&i.Folder,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
	)
	return i, err
}
